### ISSUE TITLE
Documentation: "for" values are all the same

### ISSUE THREAD

**Issue by CREEATION** [tmwagency/kickoff#41]
Hello,

the "for" values for the inputs at http://tmwagency.github.io/kickoff/demos/forms.html are all the same, for example `for="text"`, which results in jumping all the way to the top of the first input where it got declared.

Thomas

**Comment by ashleynolan** [comment]
Thanks for this Thomas – I’ll take a look into that now.

**Comment by mrmartineau** [comment]
Thanks for notifying us @CREEATION. How are you getting on with Kickoff?

**Comment by CREEATION** [comment]
Thanks for the fast update!
@mrmartineau I didn't download it yet, but it looked promising so I was walking through the documentation to get a feel of how it works. Testing it later :)

**Comment by mrmartineau** [comment]
Cool, if you need any help, please let us know. Kickoff also has a Twitter account for news & any questions: [@TMWKickoff](https://twitter.com/TMWKickoff) :+1:
