### ISSUE TITLE
Functions and mixins imports should be above the variables and color-palette imports in the styleguide.scss

### ISSUE THREAD

**Issue by ashleynolan** [tmwagency/kickoff#44]
Need to switch the order around as otherwise the variables and color-palette files cannot use any of the functions and mixins if needed.

https://github.com/tmwagency/kickoff/blob/master/scss/styleguide.scss

**Comment by mrmartineau** [comment]
Do the variables and color palette files need access to the mixins/functions? Maybe the variables need the modular scale function, is that it?

**Comment by ashleynolan** [comment]
Not from the start, but if you add code into the variables that require a mixin/function the compilation subsequently breaks.  Switching the order resolves this.

I’ll update this now as it’s a simple task.
