### ISSUE TITLE
Should round up the value of the typography scale values in variables by using ceil

### ISSUE THREAD

**Issue by ashleynolan** [tmwagency/kickoff#45]
The values produced by the modular scale for type should be rounded up so that the pixel equivalents are whole numbers, rather than to 3 or 4 dp as some of them are calculated.  Makes the compiled CSS much more standard.

https://github.com/tmwagency/kickoff/blob/master/scss/_variables.scss#L30

**Comment by mrmartineau** [comment]
I have never found this to be an issue before but I think it is a good idea. The font-sizes are generated using our [modular scale function](https://github.com/tmwagency/kickoff/blob/master/scss/functions/_modular-scale.scss) so we'd just need to tweak that to get the desired output.

I think we'd just need to change [this line](https://github.com/tmwagency/kickoff/blob/master/scss/functions/_modular-scale.scss#L66) from:

```scss
@return $value;
```

to

```scss
@return ceil($value);
```

See SassScript docs: http://sass-lang.com/documentation/Sass/Script/Functions.html#ceil-instance_method

**Comment by mrmartineau** [comment]
@ashleynolan I tried a quick test for this, see it at http://quick.as/vmr4cq8yw & let me know if you think it is acceptable.

**Comment by ashleynolan** [comment]
Looks good to me :)

**Comment by ashleynolan** [comment]
Closing as fixed from previous commit
