### ISSUE TITLE
Reconsider the structure of specific color variables in Kickoff

### ISSUE THREAD

**Issue by ashleynolan** [tmwagency/kickoff#46]
Having been using Kickoff for more minimal sites lately, I’ve found that it can be a bit of a chore when removing parts that are not needed to not simply be able to remove the specific scss from the dependencies.scss and not be left with any artifacts anywhere else.

However, you then also have to go into color-palette.scss and variables.scss and remove variables specific to these features.

As a possible enhancement, would be good to talk over the possibility of moving these variables to the top of their respective component files.  I feel it also could make the color-palette.scss more clear for new users and not be quite as full-on, as I think it’s becoming a bit unclear on which variables are the most important being used in a build.

Thoughts?

**Comment by mrmartineau** [comment]
I like this idea. It seems logical to move component vars into their own files.
